baseURL = "https://cliffchew84.github.io"
languageCode = "en-us"
title = "Cliff Chew"
theme = "anubis"
paginate = 3

disqusShortname = "cliffchew84"
googleAnalytics = "UA-168780016-1"

[author]
  name = "Cliff Chew Kuo Ting"

[params]
   author = "Cliff Chew Kuo Ting"
   description = "A Singaporean's blog on data, tech startups and societies"
   env = 'production'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Archive"
    identifier = "archive"
    url = "/posts/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
